#JDK=jdk1.6.0_18
JDKPATH=/usr/lib/jvm/java-6-sun-1.6.0.15
JDKPATH=
JDKBIN=$(JDKPATH)/bin/
JDKBIN=
JAVALIB= $(JDKPATH)/lib/jvm.lib
#CFLAGS = -c
CC=g++
#CFLAGS += -mno-cygwin
#LDFLAGS += -mno-cygwin -lwsock32
LINK=ld

# Default target
all: ctag

# Classpath for running Java
R := $(shell pwd)
S := $R/build/install/javi/lib
export CLASSPATH=$R/build/classes/java/main:$S/juniversalchardet-2.4.0.jar:$S/rhino-1.7.14.jar

#==============================================================================
# Build targets
#==============================================================================

# Compile Java sources (warnings are errors by default)
compile:
	./gradlew compileJava

# Clean build artifacts
clean:
	./gradlew clean

# Build JAR file
jar:
	./gradlew jar

# Build fat JAR with all dependencies
fatjar:
	./gradlew shadowJar

#==============================================================================
# I3: Release Distribution Targets
#==============================================================================

# Version from git describe (tag-commits-hash) or 'dev' if no tags
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")

# Copy JAR to dist directory
dist: jar plugins
	./gradlew distAll

# Build all plugin JARs
plugins: compile
	./gradlew plugins

# Copy fat JAR to dist directory  
dist-fat: fatjar
	./gradlew distFat

# Verify working directory is clean (no uncommitted changes)
verify-clean:
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "Error: Working directory not clean. Commit or stash changes first."; \
		git status --short; \
		exit 1; \
	fi
	@echo "✓ Working directory clean"

# Create a release distribution (legacy — kept for compatibility)
dist-release: verify-clean compile test
	@echo ""
	@echo "Building release $(VERSION)..."
	@mkdir -p dist
	./gradlew jar -Pversion=$(VERSION)
	cp build/libs/javi-$(VERSION).jar dist/
	@echo ""
	@echo "✓ Created: dist/javi-$(VERSION).jar"

# Create a release with fat JAR (includes all dependencies)
dist-release-fat: verify-clean compile test
	@echo ""
	@echo "Building fat release $(VERSION)..."
	@mkdir -p dist
	./gradlew shadowJar -Pversion=$(VERSION)
	cp build/libs/javi-all-$(VERSION).jar dist/
	@echo ""
	@echo "✓ Created: dist/javi-all-$(VERSION).jar"

# Show current version
version:
	@echo "Current version: $(VERSION)"

#==============================================================================
# F35: Release & Install Targets
#==============================================================================

# Create a verified, tagged release
# Usage: make release TAG=v1.0.0
#
# Steps:
#   1. Verifies TAG is provided
#   2. Verifies working directory is clean
#   3. Compiles and runs all tests
#   4. Creates versioned fat JAR (all dependencies bundled)
#   5. Creates install distribution (bin/javi launcher + lib/)
#   6. Creates annotated git tag
release:
	@test -n "$(TAG)" || { echo "Usage: make release TAG=v1.0.0"; exit 1; }
	$(MAKE) verify-clean
	$(MAKE) compile
	./gradlew test
	@echo ""
	@echo "Building release $(TAG)..."
	./gradlew shadowJar -Pversion=$(TAG:v%=%)
	./gradlew installDist -Pversion=$(TAG:v%=%)
	@mkdir -p dist
	cp build/libs/javi-all-$(TAG:v%=%).jar dist/javi-$(TAG).jar
	@echo ""
	@echo "✓ Fat JAR:    dist/javi-$(TAG).jar"
	@echo "✓ Install tree: build/install/javi/"
	@echo ""
	git tag -a $(TAG) -m "Release $(TAG)"
	@echo "✓ Created git tag: $(TAG)"
	@echo ""
	@echo "To install locally: make install"

# Install prefix (default: ~/.local)
PREFIX ?= $(HOME)/.local

# Install javi to PREFIX
# Uses Gradle application plugin's installDist to generate a proper launcher
# script with classpath handling, then copies to PREFIX.
#
# Layout:
#   PREFIX/share/javi/bin/javi   — launcher script (generated by Gradle)
#   PREFIX/share/javi/lib/*.jar  — application JARs
#   PREFIX/bin/javi              — symlink to launcher
#
# Usage:
#   make install                 # installs to ~/.local
#   make install PREFIX=/opt/javi
install: plugins
	./gradlew installDist
	@# Copy plugin JARs into the installDist tree so they're found
	@# when running from build/install/javi/bin/javi directly
	@for jar in build/libs/javi-*.jar; do \
		case "$$jar" in build/libs/javi-dev*.jar|build/libs/javi-all*.jar) continue;; esac; \
		cp "$$jar" build/install/javi/lib/; \
	done
	@echo "Installing to $(PREFIX)..."
	@mkdir -p $(PREFIX)/bin $(PREFIX)/share/javi
	rm -rf $(PREFIX)/share/javi/bin $(PREFIX)/share/javi/lib
	cp -R build/install/javi/bin $(PREFIX)/share/javi/
	cp -R build/install/javi/lib $(PREFIX)/share/javi/
	cp javi-cl $(PREFIX)/bin/javi-cl
	chmod +x $(PREFIX)/bin/javi-cl
	ln -sf ../share/javi/bin/javi $(PREFIX)/bin/javi
	@echo ""
	@echo "✓ Installed to $(PREFIX)/share/javi/"
	@echo "✓ Launcher:   $(PREFIX)/bin/javi"
	@echo "✓ Client:     $(PREFIX)/bin/javi-cl"
	@echo ""
	@if ! echo "$$PATH" | tr ':' '\n' | grep -qx '$(PREFIX)/bin'; then \
		echo "Add $(PREFIX)/bin to your PATH:"; \
		echo "  export PATH=\"$(PREFIX)/bin:\$$PATH\""; \
		echo ""; \
	fi

# Remove javi from PREFIX
uninstall:
	rm -f $(PREFIX)/bin/javi $(PREFIX)/bin/javi-cl
	rm -rf $(PREFIX)/share/javi
	@echo "✓ Uninstalled javi from $(PREFIX)"

# Full build (compile + jar + plugin JARs)
build: compile jar
	./gradlew plugins

#==============================================================================
# Test targets
#==============================================================================

.PHONY: FORCE docs
FORCE:

ai.output:
	mkdir -p $@

ai.output/junit.out: FORCE | ai.output
	./gradlew test > $@ 2>&1

ai.output/test.out: FORCE | ai.output
	$(MAKE) compile test-core > $@ 2>&1

# Run PSTest (PersistantStack tests)
pstest: compile
	java -cp $(CLASSPATH) history.PSTest

# Run EditTester1 (TextEdit tests)
edittest: compile
	java -cp $(CLASSPATH) javi.EditTester1

# Run IntArrayTest (IntArray tests)
intarraytest: compile
	java -ea -cp $(CLASSPATH) history.IntArrayTest

ctagtest: compile
	java -ea -cp $(CLASSPATH) javi.Ctag

# Core legacy test sequence (without wrapper)
test-core: ctagtest intarraytest pstest edittest

# Run all legacy tests and capture output
test: ai.output/test.out

# Run JUnit 5 tests via Gradle and capture output
junit: ai.output/junit.out

# Run tests that are excluded from 'make junit' (lsp-live integration tests)
# These require external tools (jdtls, clangd) installed on PATH.
junit-skipped:
	./gradlew lspLiveTest --console=plain

# Compile test sources
compile-test:
	./gradlew compileTestJava

# Run GUI tests (AssertJ Swing — requires display/Xvfb)
guitest:
	./gradlew guiTest

#==============================================================================
# Remote GUI testing (rdesk + Docker)
#==============================================================================

RDESK_GUITEST_DIR = /tmp/javi-guitest
GUITEST_IMAGE = javi-guitest

GUITEST_EXCLUDE = --exclude='build/' --exclude=.gradle --exclude=.git \
   --exclude='*.dmp2' --exclude=ai.output --exclude='ai/*.out' \
   --exclude=bin --exclude=oldstuff --exclude=tmp

# Full pipeline: sync, build Docker image, run GUI tests, fetch results
rdesk-guitest: rdesk-guitest-sync rdesk-guitest-build rdesk-guitest-run rdesk-guitest-fetch

# Sync javi source to rdesk
rdesk-guitest-sync:
	@mkdir -p plugins
	rsync -az --delete $(GUITEST_EXCLUDE) ./ rdesk:$(RDESK_GUITEST_DIR)/

# Build Docker image on rdesk
rdesk-guitest-build: rdesk-guitest-sync
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   docker build -f Dockerfile.guitest -t $(GUITEST_IMAGE) .'

# Run GUI tests on rdesk via Docker
rdesk-guitest-run: rdesk-guitest-build
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   mkdir -p build && \
	   docker run --rm \
	      --user $$(id -u):$$(id -g) \
	      -v $$(pwd)/build:/app/build \
	      $(GUITEST_IMAGE)'

# Fetch test results from rdesk
rdesk-guitest-fetch:
	rsync -az rdesk:$(RDESK_GUITEST_DIR)/build/reports/ \
	   build/reports-rdesk/ 2>/dev/null || true
	rsync -az rdesk:$(RDESK_GUITEST_DIR)/build/test-results/ \
	   build/test-results-rdesk/ 2>/dev/null || true
	@mkdir -p build/jacoco
	rsync -az rdesk:$(RDESK_GUITEST_DIR)/build/jacoco/ \
	   build/jacoco/ 2>/dev/null || true

# Clean remote Docker image and files
rdesk-guitest-clean:
	ssh -n -T rdesk 'docker rmi $(GUITEST_IMAGE) 2>/dev/null; \
	   rm -rf $(RDESK_GUITEST_DIR)'

#==============================================================================
# T1: Quick GUI test iteration (base image + volume mount)
#==============================================================================
#
# Workflow for fast iteration:
#   1. make rdesk-guitest-base    (once — builds base image with JDK/Xvfb/deps)
#   2. make rdesk-guitest-quick   (sync + run — no docker build, incremental)
#   3. fix tests
#   4. make rdesk-guitest-quick   (repeat — Gradle does incremental compile)
#
# For a clean rebuild: make rdesk-guitest-quick-clean
# For headless + GUI:  make rdesk-guitest-quick GUITEST_TASKS="test guiTest"
# For clean + GUI:     make rdesk-guitest-quick GUITEST_TASKS="clean guiTest"

GUITEST_BASE_IMAGE = javi-guitest-base
GUITEST_TASKS ?= guiTest

# Build base image (JDK + Xvfb + Gradle deps cached). Run once.
rdesk-guitest-base: rdesk-guitest-sync
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   docker build -f Dockerfile.guitest-base -t $(GUITEST_BASE_IMAGE) .'

# Quick test run: sync source, copy into container filesystem, run tests.
# Source is copied from bind-mount to image fs because Gradle's JUnit test
# worker exits prematurely when running directly from a bind mount.
# Build output goes to host via -v build:/app/build.
rdesk-guitest-quick: rdesk-guitest-sync
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   docker run --rm -v $$(pwd):/w alpine \
	      sh -c "rm -rf /w/.git; find /w/.gradle -name \"*.lock\" -delete 2>/dev/null; mkdir -p /w/.gradle /w/build; chown $$(id -u):$$(id -g) /w/.gradle /w/build" && \
	   docker run --rm \
	      -v $$(pwd):/src \
	      -v $$(pwd)/build:/app/build \
	      --entrypoint "" \
	      $(GUITEST_BASE_IMAGE) \
	      sh -c "cp -r /src/src /app/src && cp /src/build.gradle /app/ && /usr/local/bin/docker-entrypoint.sh $(GUITEST_TASKS)"'
	$(MAKE) rdesk-guitest-fetch
	@rsync -az rdesk:$(RDESK_GUITEST_DIR)/build/guitest-output.txt build/ 2>/dev/null || true
	@rsync -az rdesk:$(RDESK_GUITEST_DIR)/build/guitest-summary.txt build/ 2>/dev/null || true
	@echo ""
	@if [ -f build/guitest-summary.txt ]; then cat build/guitest-summary.txt; \
	elif [ -f build/guitest-output.txt ]; then sh ai/parse-guitest.sh build/guitest-output.txt; fi

# Clean: remote build artifacts but keep base image
rdesk-guitest-quick-clean:
	ssh -n -T rdesk 'rm -rf $(RDESK_GUITEST_DIR)/build $(RDESK_GUITEST_DIR)/.gradle'

# Parse results from last run (no remote access needed)
rdesk-guitest-report:
	@sh ai/parse-guitest.sh build/guitest-output.txt

#==============================================================================
# T1: Remote Docker all-tests (headless JUnit + GUI tests via Xvfb)
#==============================================================================

ALLTEST_IMAGE = javi-alltest

# Full pipeline: sync, build Docker image, run ALL tests, fetch results
rdesk-alltest: rdesk-guitest-sync rdesk-alltest-build rdesk-alltest-run rdesk-guitest-fetch

# Build all-test Docker image on rdesk
# Use --build-arg to bust Docker layer cache when source changes
rdesk-alltest-build: rdesk-guitest-sync
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   docker build --build-arg SRC_HASH=$$(find src -type f -newer Dockerfile.alltest -print | wc -l) \
	      -f Dockerfile.alltest -t $(ALLTEST_IMAGE) .'

# Run ALL tests on rdesk via Docker
rdesk-alltest-run: rdesk-alltest-build
	ssh -n -T rdesk 'cd $(RDESK_GUITEST_DIR) && \
	   mkdir -p build && \
	   docker run --rm \
	      --user $$(id -u):$$(id -g) \
	      -v $$(pwd)/build:/app/build \
	      $(ALLTEST_IMAGE)'

# Clean all-test Docker image
rdesk-alltest-clean:
	ssh -n -T rdesk 'docker rmi $(ALLTEST_IMAGE) 2>/dev/null'

#==============================================================================
# F22: Remote Docker esctest2 (VT100 compliance tests via Xvfb)
#==============================================================================

ESCTEST_IMAGE = javi-esctest2
RDESK_ESCTEST_DIR = /tmp/javi-esctest2

# Full pipeline: sync, build Docker image, run esctest2, fetch results
rdesk-esctest2: rdesk-esctest2-sync rdesk-esctest2-build rdesk-esctest2-run rdesk-esctest2-fetch

# Sync javi source to rdesk
rdesk-esctest2-sync:
	rsync -az $(GUITEST_EXCLUDE) ./ rdesk:$(RDESK_ESCTEST_DIR)/

# Build esctest2 Docker image on rdesk
rdesk-esctest2-build: rdesk-esctest2-sync
	ssh -n -T rdesk 'cd $(RDESK_ESCTEST_DIR) && \
	   docker build --build-arg SRC_HASH=$$(find src -type f -newer Dockerfile.esctest2 -print | wc -l) \
	      -f Dockerfile.esctest2 -t $(ESCTEST_IMAGE) .'

# Run esctest2 on rdesk via Docker
rdesk-esctest2-run: rdesk-esctest2-build
	ssh -n -T rdesk 'cd $(RDESK_ESCTEST_DIR) && \
	   rm -rf results && mkdir -p results && \
	   docker run --rm \
	      -v $$(pwd)/results:/results \
	      $(ESCTEST_IMAGE)'

# Fetch esctest2 results from rdesk
rdesk-esctest2-fetch:
	@mkdir -p ai/esctest2-results
	rsync -az rdesk:$(RDESK_ESCTEST_DIR)/results/ \
	   ai/esctest2-results/ 2>/dev/null || true
	@echo "=== Results fetched to ai/esctest2-results/ ==="
	@if [ -f ai/esctest2-results/esctest2.log ]; then \
	   tail -30 ai/esctest2-results/esctest2.log; \
	fi

# Clean remote esctest2 Docker image and files
rdesk-esctest2-clean:
	ssh -n -T rdesk 'docker rmi $(ESCTEST_IMAGE) 2>/dev/null; \
	   rm -rf $(RDESK_ESCTEST_DIR)'

#==============================================================================
# F22: Remote Docker bug verification (interactive bug tests via Xvfb)
#==============================================================================

VERIFY_IMAGE = javi-verify
RDESK_VERIFY_DIR = /tmp/javi-verify

# Full pipeline: sync, build, run, fetch
rdesk-verify-bugs: rdesk-verify-sync rdesk-verify-build rdesk-verify-run rdesk-verify-fetch

# Sync source to rdesk
rdesk-verify-sync:
	rsync -az --include='build.gradle' --include='build.xml' \
	   $(GUITEST_EXCLUDE) ./ rdesk:$(RDESK_VERIFY_DIR)/

# Build verify Docker image on rdesk
rdesk-verify-build: rdesk-verify-sync
	ssh -n -T rdesk 'cd $(RDESK_VERIFY_DIR) && \
	   docker build --build-arg SRC_HASH=$$(find src -type f -newer Dockerfile.verify -print | wc -l) \
	      -f Dockerfile.verify -t $(VERIFY_IMAGE) .'

# Run verification on rdesk
rdesk-verify-run: rdesk-verify-build
	ssh -n -T rdesk 'cd $(RDESK_VERIFY_DIR) && \
	   rm -rf results && mkdir -p results && \
	   docker run --rm \
	      -v $$(pwd)/results:/results \
	      $(VERIFY_IMAGE)'

# Fetch results from rdesk
rdesk-verify-fetch:
	@mkdir -p ai/verify-results
	rsync -az rdesk:$(RDESK_VERIFY_DIR)/results/ \
	   ai/verify-results/ 2>/dev/null || true
	@echo "=== Results fetched to ai/verify-results/ ==="
	@if [ -f ai/verify-results/verify-bugs.txt ]; then \
	   cat ai/verify-results/verify-bugs.txt; \
	fi

# Clean remote verify Docker image and files
rdesk-verify-clean:
	ssh -n -T rdesk 'docker rmi $(VERIFY_IMAGE) 2>/dev/null; \
	   rm -rf $(RDESK_VERIFY_DIR)'

#==============================================================================
# F43: CPU measurement (Dockerfile.cpumeasure on rdesk)
#==============================================================================

CPUMEASURE_IMAGE = javi-cpumeasure
RDESK_CPUMEASURE_DIR = /tmp/javi-cpumeasure

# Full pipeline: sync, build Docker image, run measurement, fetch results
rdesk-cpu-measure: rdesk-cpu-sync rdesk-cpu-build rdesk-cpu-run rdesk-cpu-fetch

# Sync javi source to rdesk
rdesk-cpu-sync:
	rsync -az --delete $(GUITEST_EXCLUDE) ./ rdesk:$(RDESK_CPUMEASURE_DIR)/

# Build CPU measurement Docker image on rdesk
rdesk-cpu-build: rdesk-cpu-sync
	ssh -n -T rdesk 'cd $(RDESK_CPUMEASURE_DIR) && \
	   docker build -f Dockerfile.cpumeasure -t $(CPUMEASURE_IMAGE) .'

# Run CPU measurement on rdesk
rdesk-cpu-run: rdesk-cpu-build
	ssh -n -T rdesk 'cd $(RDESK_CPUMEASURE_DIR) && \
	   mkdir -p results && \
	   docker run --rm $(CPUMEASURE_IMAGE) | tee results/cpu-measure.txt'

# Fetch CPU measurement results from rdesk
rdesk-cpu-fetch:
	@mkdir -p ai/cpu-results
	rsync -az rdesk:$(RDESK_CPUMEASURE_DIR)/results/ \
	   ai/cpu-results/ 2>/dev/null || true
	@echo "=== CPU Measurement Results ==="
	@if [ -f ai/cpu-results/cpu-measure.txt ]; then \
	   cat ai/cpu-results/cpu-measure.txt; \
	fi

# Clean CPU measurement Docker image and files
rdesk-cpu-clean:
	ssh -n -T rdesk 'docker rmi $(CPUMEASURE_IMAGE) 2>/dev/null; \
	   rm -rf $(RDESK_CPUMEASURE_DIR)'

# Run PSTest with coverage and generate report
pstest-coverage:
	./gradlew pstestCoverage
	java -jar lib/org.jacoco.cli-0.8.12-nodeps.jar report build/jacoco/pstest.exec \
		--classfiles build/classes/java/main \
		--sourcefiles src/main/java --sourcefiles src/history/java \
		--html build/reports/coverage-pstest
	@echo "Coverage report: build/reports/coverage-pstest/index.html"
	@echo "NOTE: For full coverage including JUnit tests, use 'make test-coverage'"

# Run all tests with coverage and generate merged report
test-coverage:
	./gradlew test pstestCoverage intArrayTestCoverage mergedCoverageReport
	@echo "Merged coverage report: build/reports/jacoco/merged/html/index.html"

# Run test-coverage then parse XML into text summary
coverage-report: test-coverage compile
	java -cp build/classes/java/main javi.CoverageReport \
	   build/reports/jacoco/merged/merged.xml

#==============================================================================
# T3: GUI Coverage Targets (JaCoCo agent + tcpserver)
#==============================================================================

# Resolve JaCoCo agent JAR path from Gradle
JACOCO_AGENT = $(shell ./gradlew -q jacocoAgentPath 2>/dev/null)

# Launch javi with JaCoCo agent (coverage via tcpserver on port 6300)
# Usage: make run-coverage [FILE=myfile.txt]
# After exercising the GUI, run: make coverage-dump
run-coverage: compile
	@echo "Starting javi with JaCoCo coverage agent (port 6300)..."
	@echo "Use the editor, then run 'make coverage-dump' before quitting."
	java -javaagent:$(JACOCO_AGENT)=output=tcpserver,port=6300,address=127.0.0.1 \
	   -cp $(CLASSPATH) javi.Javi $(FILE)

# Dump coverage from running javi (must be started with run-coverage)
coverage-dump:
	./gradlew jacocoDump
	@echo "Coverage dumped to build/jacoco/gui.exec"

# Merge all .exec files (JUnit + legacy + GUI) and generate report
# Note: Local-only — excludes GUI tests (need display). For full coverage
# including GUI tests, use: make rdesk-alltest  (generates Docker report)
coverage-merge:
	./gradlew mergedCoverageReport
	@echo "Merged coverage report: build/reports/jacoco/merged/html/index.html"

# Full coverage workflow: JUnit + legacy tests + merge report
# If gui.exec exists (from prior run-coverage + coverage-dump), it's included
full-coverage: compile
	./gradlew test pstestCoverage intArrayTestCoverage mergedCoverageReport
	@echo "Merged coverage report: build/reports/jacoco/merged/html/index.html"

# Full coverage including GUI tests via rdesk Docker
# Docker generates the merged report with consistent class files.
# Report fetched to build/reports-rdesk/jacoco/merged/html/index.html
rdesk-coverage: rdesk-alltest
	@echo "Full coverage report (including GUI): build/reports-rdesk/jacoco/merged/html/index.html"

#==============================================================================
# Run targets
#==============================================================================

# Run the application (GUI mode)
run: compile
	java -cp $(CLASSPATH) javi.Javi

# Run with specific file
# Usage: make run-file FILE=myfile.txt
run-file: compile
	java -cp $(CLASSPATH) javi.Javi $(FILE)

#==============================================================================
# Code quality targets
#==============================================================================

# Run checkstyle on modified Java files
cstyle:
	perl cstyle src/main/java/javi/*.java src/history/java/history/*.java

# Run checkstyle on a specific file
# Usage: make cstyle-file FILE=src/main/java/javi/Javi.java
cstyle-file:
	perl cstyle $(FILE)

# Run checkstyle without filter (all violations are errors)
# Usage: make cstyle-nofilter              (all files)
#        make cstyle-nofilter FILE=<path>  (single file)
cstyle-nofilter:
ifdef FILE
	perl cstyle --nofilter $(FILE)
else
	perl cstyle --nofilter src/main/java/javi/*.java src/history/java/history/*.java
endif

# Show lines longer than 90 characters in a file
# Usage: make longlines FILE=src/main/java/javi/Javi.java
longlines:
	awk 'length > 90 {printf "%d: %d: %s\n", NR, length, $$0}' $(FILE)

#==============================================================================
# Documentation targets
#==============================================================================

# Build Typst documentation (PDF)
docs:
	typst compile docs/javi_manual.typ docs/javi_manual.pdf
	@echo "PDF generated: docs/javi_manual.pdf"

# Generate Javadoc documentation
javadoc:
	mkdir -p build/docs/javadoc
	javadoc -d build/docs/javadoc \
		-sourcepath src/main/java:src/history/java \
		-classpath lib/rhino-1.7.14.jar:lib/juniversalchardet-1.0.3.jar:lib/rxtx-2.1.7.jar \
		-subpackages javi:history \
		-windowtitle "Javi Editor API" \
		-doctitle "Javi - Vi-like Editor in Java" \
		-header "Javi Editor" \
		-quiet \
		-Xdoclint:none
	@echo "Javadoc generated: build/docs/javadoc/index.html"

#==============================================================================
# Development utility targets
#==============================================================================

PORCE:
# Generate tags for code navigation
tags: FORCE
	ctags -n -R src

# Generate ID database for gid/lid
ID: FORCE
	mkid -m ~/cyghome/id-lang.map src

# Update both tags and ID
id: tags ID

#==============================================================================
# Legacy targets (kept for compatibility)
#==============================================================================

jarf=build/libs/javi-all.jar

gbuild: compile

automake: runclass #runclass

runner: jar
	java -cp $(CLASSPATH) -jar build/libs/javi-1.0.jar

runclass:
	echo CLASSPATH $$CLASSPATH
	java  -cp $(CLASSPATH) javi.Javi testfile #src history main java javi awt history

FORCE:

#==============================================================================
# Help
#==============================================================================

help:
	@echo "Javi Makefile Targets:"
	@echo ""
	@echo "Build:"
	@echo "  make compile      - Compile Java sources (warnings are errors)"
	@echo "  make jar          - Build JAR file"
	@echo "  make fatjar       - Build fat JAR with dependencies"
	@echo "  make build        - Full build (compile + jar)"
	@echo "  make clean        - Clean build artifacts"
	@echo ""
	@echo "Distribution:"
	@echo "  make dist         - Copy JAR to dist/ directory"
	@echo "  make dist-fat     - Copy fat JAR to dist/ directory"
	@echo "  make version      - Show current version from git"
	@echo ""
	@echo "Release & Install:"
	@echo "  make release TAG=v1.0.0 - Verified release (test + fat JAR + git tag)"
	@echo "  make install            - Install to ~/.local (PREFIX=path to override)"
	@echo "  make uninstall          - Remove from ~/.local (PREFIX=path to override)"
	@echo ""
	@echo "Test:"
	@echo "  make test         - Run all tests"
	@echo "  make pstest       - Run PersistantStack tests"
	@echo "  make edittest     - Run EditTester1 tests"
	@echo "  make intarraytest - Run IntArray tests"
	@echo "  make test-coverage - Run tests with coverage report"
	@echo ""
	@echo "Run:"
	@echo "  make run          - Run the application"
	@echo "  make run-file FILE=path/to/file - Run with specific file"
	@echo ""
	@echo "Code Quality:"
	@echo "  make cstyle       - Run checkstyle on all Java files"
	@echo "  make cstyle-file FILE=path - Run checkstyle on specific file"
	@echo ""
	@echo "Documentation:"
	@echo "  make docs         - Build Typst manual (PDF)"
	@echo "  make javadoc      - Generate Javadoc documentation"
	@echo ""
	@echo "Development:"
	@echo "  make tags         - Generate ctags"
	@echo "  make ID           - Generate ID database"
	@echo "  make help         - Show this help"
