package javi;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Roundtrip coverage tests for {@link KeyBindingPersistence}.
 *
 * <p>Exercises the {@code save()} and {@code load()} method bodies
 * by:</p>
 * <ul>
 *   <li>Redirecting {@code user.home} to a temp directory so the
 *       config file write is isolated.</li>
 *   <li>Injecting a test {@code normalKeyMap} via reflection so
 *       {@code save()} executes its body (default test environment
 *       leaves {@code normalKeyMap} null because
 *       {@code MapEvent.bindCommands()} is skipped — see
 *       {@link TestInit}).</li>
 * </ul>
 */
class KeyBindingPersistenceRoundtripJUnitTest {

   @TempDir
   Path tempHome;

   private String savedHome;
   private Object savedNormal;
   private Field normalField;

   @BeforeAll
   static void initOnce() throws Exception {
      TestInit.initCommands();
   }

   @BeforeEach
   void setup() throws Exception {
      EventQueue.biglock2.lock();
      savedHome = System.getProperty("user.home");
      System.setProperty("user.home", tempHome.toString());
      // Inject a test normal keymap so save() runs its body.
      normalField = MapEvent.class.getDeclaredField("normalKeyMap");
      normalField.setAccessible(true);
      savedNormal = normalField.get(null);
      KeyGroup move = new KeyGroup("rt-normal-move");
      KeyGroup edit = new KeyGroup("rt-normal-edit");
      KeyMap testKm = new KeyMap("rt-normal", move, edit);
      normalField.set(null, testKm);
   }

   @AfterEach
   void teardown() throws Exception {
      try {
         normalField.set(null, savedNormal);
         if (savedHome != null)
            System.setProperty("user.home", savedHome);
      } finally {
         EventQueue.biglock2.unlock();
      }
   }

   // ── save() body coverage ──────────────────────────────────

   @Test
   void saveWritesMoveAndEditBindings() throws IOException {
      KeyMap km = MapEvent.getNormalKeyMap();
      assertNotNull(km, "test keymap should be injected");
      km.getMoveKeys().bind(
         new JeyEvent(0, 0, 'h'), "movechar", null);
      km.getEditKeys().bind(
         new JeyEvent(0, 0, 'i'), "insert", null);

      int count = KeyBindingPersistence.save();
      assertTrue(count >= 2,
         "at least two bindings should be saved (got " + count + ")");

      Path file = KeyBindingPersistence.getConfigPath();
      assertTrue(Files.exists(file),
         "config file should be created under temp home");
      String content = Files.readString(file, StandardCharsets.UTF_8);
      assertTrue(content.contains("mapkey move h movechar"),
         "file should contain move binding line");
      assertTrue(content.contains("mapkey edit i insert"),
         "file should contain edit binding line");
      assertTrue(content.contains("# Javi user keybindings"),
         "file should start with header comment");
      assertTrue(content.contains("# Format:"),
         "file should contain format comment");
      assertTrue(content.contains("# Generated by :savemapkeys"),
         "file should contain generator comment");
   }

   @Test
   void saveCreatesParentDirectory() throws IOException {
      KeyMap km = MapEvent.getNormalKeyMap();
      km.getMoveKeys().bind(
         new JeyEvent(0, 0, 'q'), "movechar", null);

      Path file = KeyBindingPersistence.getConfigPath();
      assertFalse(Files.exists(file.getParent()),
         "parent dir should not exist before save");
      int count = KeyBindingPersistence.save();
      assertTrue(count >= 1,
         "save returns >=1 when at least one binding exists");
      assertTrue(Files.exists(file.getParent()),
         "save() should create ~/.javi parent directory");
   }

   @Test
   void saveEarlyReturnPathExecutes() throws IOException {
      // Empty test keymap; overlay state is global so we can't
      // assert zero bindings overall, but we can exercise the
      // save() path and verify return is non-negative and
      // consistent (no exception, no NPE).
      int count = KeyBindingPersistence.save();
      assertTrue(count >= 0,
         "save returns non-negative count");
   }

   @Test
   void saveIncludesOverlayBindings() throws IOException {
      KeyMap km = MapEvent.getNormalKeyMap();
      // Create an overlay on top of our test normal map
      KeyMap overlay =
         KeyMap.createOverlay("rt-overlay", km);
      KeyMap.register(overlay);
      try {
         overlay.getMoveKeys().bind(
            new JeyEvent(0, 0, 'g'), "movechar", null);
         overlay.getEditKeys().bind(
            new JeyEvent(0, 0, 'p'), "insert", null);

         int count = KeyBindingPersistence.save();
         assertTrue(count >= 2,
            "overlay bindings should be saved (got " + count + ")");

         String content = Files.readString(
            KeyBindingPersistence.getConfigPath(),
            StandardCharsets.UTF_8);
         assertTrue(content.contains("rt-overlay.move g movechar"),
            "file should contain overlay-prefixed move binding");
         assertTrue(content.contains("rt-overlay.edit p insert"),
            "file should contain overlay-prefixed edit binding");
      } finally {
         // Best-effort cleanup of the test overlay
         overlay.getMoveKeys().unbind(new JeyEvent(0, 0, 'g'));
         overlay.getEditKeys().unbind(new JeyEvent(0, 0, 'p'));
      }
   }

   @Test
   void saveCombinesNormalAndOverlay() throws IOException {
      KeyMap km = MapEvent.getNormalKeyMap();
      km.getMoveKeys().bind(
         new JeyEvent(0, 0, 'h'), "movechar", null);

      KeyMap overlay =
         KeyMap.createOverlay("rt-overlay2", km);
      KeyMap.register(overlay);
      try {
         overlay.getEditKeys().bind(
            new JeyEvent(0, 0, 'a'), "insert", null);

         int count = KeyBindingPersistence.save();
         assertTrue(count >= 2,
            "normal+overlay bindings should be saved (got " + count + ")");

         String content = Files.readString(
            KeyBindingPersistence.getConfigPath(),
            StandardCharsets.UTF_8);
         assertTrue(content.contains("mapkey move h movechar"));
         assertTrue(
            content.contains("rt-overlay2.edit a insert"));
      } finally {
         overlay.getEditKeys().unbind(new JeyEvent(0, 0, 'a'));
      }
   }

   // ── load() body coverage ──────────────────────────────────

   @Test
   void loadReturnsZeroWhenFileMissing() {
      // tempHome is fresh so ~/.javi/keybindings does not exist
      int count = KeyBindingPersistence.load();
      assertEquals(0, count,
         "load with no file returns 0");
   }

   @Test
   void loadSkipsCommentsAndBlankLines() throws IOException {
      Path file = KeyBindingPersistence.getConfigPath();
      Files.createDirectories(file.getParent());
      Files.writeString(file,
         "# header comment\n"
         + "\n"
         + "# another comment\n"
         + "   \n",
         StandardCharsets.UTF_8);

      int count = KeyBindingPersistence.load();
      assertEquals(0, count,
         "load with only comments/blank lines returns 0");
   }

   @Test
   void loadCountsNonCommentLines() throws IOException {
      // Even if Command.command() fails internally, load()
      // counts each non-comment, non-blank line attempted.
      Path file = KeyBindingPersistence.getConfigPath();
      Files.createDirectories(file.getParent());
      // Use a benign command that will be looked up via excmd.
      // The exact command doesn't matter — failures are swallowed
      // inside Command.command's dispatch; load() only counts.
      Files.writeString(file,
         "# comment\n"
         + "echo testline1\n"
         + "echo testline2\n",
         StandardCharsets.UTF_8);

      int count = KeyBindingPersistence.load();
      assertEquals(2, count,
         "load counts non-comment, non-blank lines");
   }
}
