package javi;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static history.Tools.trace;

/**
 * Persistence for user-customized key bindings.
 *
 * <p>Saves and loads runtime keybinding modifications (those made via
 * {@code :mapkey}) to/from a configuration file. The default location
 * is {@code ~/.javi/keybindings}.</p>
 *
 * <h2>File format</h2>
 * <pre>
 * # Lines starting with # are comments
 * # Format: mapkey &lt;group&gt; &lt;keyspec&gt; &lt;command&gt;
 * mapkey move h movechar
 * mapkey edit C-a append
 * </pre>
 *
 * <p>The format is intentionally compatible with the {@code :mapkey}
 * command so each line can be executed as a colon command during
 * startup.</p>
 *
 * @see MiscCommands
 * @see KeyGroup
 */
final class KeyBindingPersistence {

   private static final String CONFIG_DIR = ".javi";
   private static final String CONFIG_FILE = "keybindings";

   private KeyBindingPersistence() {
   }

   /**
    * Get the path to the keybinding config file.
    *
    * @return path to ~/.javi/keybindings
    */
   static Path getConfigPath() {
      String home = System.getProperty("user.home");
      return Path.of(home, CONFIG_DIR, CONFIG_FILE);
   }

   /**
    * Save user-modified keybindings to the config file.
    * Creates the ~/.javi directory if it does not exist.
    *
    * @return the number of bindings saved
    * @throws IOException if writing fails
    */
   static int save() throws IOException {
      KeyMap normal = MapEvent.getNormalKeyMap();
      if (normal == null)
         return 0;

      List<String> moveSpecs = normal.getMoveKeys().getUserBindingSpecs();
      List<String> editSpecs = normal.getEditKeys().getUserBindingSpecs();

      // Collect overlay keymap user bindings
      List<KeyMap> overlays = KeyMap.getOverlayKeymaps();
      java.util.Map<String, List<String>> overlayMoveSpecs =
         new java.util.LinkedHashMap<>();
      java.util.Map<String, List<String>> overlayEditSpecs =
         new java.util.LinkedHashMap<>();
      for (KeyMap km : overlays) {
         List<String> oMove = km.getMoveKeys().getUserBindingSpecs();
         List<String> oEdit = km.getEditKeys().getUserBindingSpecs();
         if (!oMove.isEmpty())
            overlayMoveSpecs.put(km.getName(), oMove);
         if (!oEdit.isEmpty())
            overlayEditSpecs.put(km.getName(), oEdit);
      }

      boolean hasNormal = !moveSpecs.isEmpty() || !editSpecs.isEmpty();
      boolean hasOverlays = !overlayMoveSpecs.isEmpty()
         || !overlayEditSpecs.isEmpty();

      if (!hasNormal && !hasOverlays)
         return 0;

      Path configPath = getConfigPath();
      Files.createDirectories(configPath.getParent());

      int count = 0;
      try (BufferedWriter writer = Files.newBufferedWriter(
            configPath, StandardCharsets.UTF_8)) {
         writer.write("# Javi user keybindings");
         writer.newLine();
         writer.write("# Format: mapkey <group> <keyspec> <command>");
         writer.newLine();
         writer.write("# Overlay: mapkey <keymap>.<group> <keyspec> <command>");
         writer.newLine();
         writer.write("# Generated by :savemapkeys");
         writer.newLine();
         writer.newLine();

         // Normal keymap bindings
         for (String spec : moveSpecs) {
            writer.write("mapkey move " + spec);
            writer.newLine();
            count++;
         }
         for (String spec : editSpecs) {
            writer.write("mapkey edit " + spec);
            writer.newLine();
            count++;
         }

         // Overlay keymap bindings
         for (var entry : overlayMoveSpecs.entrySet()) {
            String kmName = entry.getKey();
            for (String spec : entry.getValue()) {
               writer.write("mapkey " + kmName + ".move " + spec);
               writer.newLine();
               count++;
            }
         }
         for (var entry : overlayEditSpecs.entrySet()) {
            String kmName = entry.getKey();
            for (String spec : entry.getValue()) {
               writer.write("mapkey " + kmName + ".edit " + spec);
               writer.newLine();
               count++;
            }
         }
      }

      trace("saved " + count + " user keybindings to " + configPath);
      return count;
   }

   /**
    * Load user keybindings from the config file.
    * Each non-comment, non-blank line is executed as a colon command.
    *
    * @return the number of bindings loaded
    */
   static int load() {
      Path configPath = getConfigPath();
      if (!Files.exists(configPath))
         return 0;

      int count = 0;
      try (BufferedReader reader = Files.newBufferedReader(
            configPath, StandardCharsets.UTF_8)) {
         for (String line; (line = reader.readLine()) != null;) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("#"))
               continue;
            Command.command(line, null, null);
            count++;
         }
      } catch (IOException e) {
         trace("error loading keybindings from " + configPath + ": " + e);
         UI.reportMessage("Error loading keybindings: " + e.getMessage());
      }

      if (count > 0)
         trace("loaded " + count + " user keybindings from " + configPath);
      return count;
   }
}
